console.log("car, cat : /cat[rt]/");
console.log(/ca[rt]/.test("car"));
console.log(/ca[rt]/.test("cat"));
console.log("pop, prop : /pr?op/");
console.log(/pr?op/.test("pop"));
console.log(/pr?op/.test("prop"));
console.log("ferret, ferry and ferrari : /ferr(et|y|ari)/");
console.log(/ferr(et|y|ari)/.test("ferrari"));
console.log(/ferr(et|y|ari)/.test("ferry"));
console.log(/ferr(et|y|ari)/.test("ferrari"));
console.log("space then . , - ;: /\s[.;\-,]/");
console.log(/ [.;\-,]/.test(" ."));
console.log(/ [.;\-,]/.test(" -"));
console.log(/ [.;\-,]/.test(" ;"));
console.log(/ [.;\-,]/.test(" ,"));
console.log("len(word) > 6: /^\w{7,}\b$/");
console.log(/.{7,}/.test("abc"));
console.log(/^\w{7,}\b$/.test("abcabcaj j"));
console.log(/^\w{7,}\b$/.test("abcabcaj"));
console.log("word wihtout E or e: /^\\b[^eE]\\b$/");
console.log(/^\b[^eE]$\b/.test("em"));
console.log(/^\b[^eE]\b$/.test("m"));
